name = "pathminty-events"
type = "web_pixel_extension"
uid = "87db231d-8f82-a767-81b0-95d4d8225b4ed18b7bdb"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.collectorUrl]
name = "Collector URL"
description = "PathMinty customer-events endpoint"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]

[settings.fields.shopId]
name = "Shop ID"
description = "The Shopify shop connected to PathMinty"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]

[settings.fields.publicToken]
name = "Storefront token"
description = "A publishable token used only for event ingestion"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "24" }
]

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"
